version = "1.8.1"

[global]
resolution = "1920x1080"
fps = "24000/1001"
timecodeFormat = "SMPTE_NON_DROP_FRAME"
blankFirstFrame = false
blankLastFrame = true
grounding = [0.0, 0.0, 0.0, 1.0, ]
unitVGapPx = 80.0
locale = "fr"
uppercaseExceptions = ["_af_", "_auf_", "_d’#", "_da_", "_Da#", "_dai_", "_Dai#", "_dal_", "_Dal#", "_dalla_", "_Dalla#", "_das_", "_de_", "_de’_", "_dei_", "_Dei#", "_del_", "_Del#", "_della_", "_Della#", "_der_", "_des_", "_di_", "_Di#", "_do_", "_dos_", "_du_", "_e_", "_Mc#", "_Mac#", "_of_", "_ten_", "_thoe_", "_til_", "_to_", "_tot_", "_van_", "_von_", "_von und zu_", "_zu_", ]

[[pageStyle]]
name = "Défilement"
subsequentGapFrames = 23
behavior = "SCROLL"
scrollPxPerFrame = 1.8

[[pageStyle]]
name = "Écran"
subsequentGapFrames = 23
behavior = "CARD"
cardRuntimeFrames = 119
cardFadeInFrames = 30
cardFadeInTransitionStyleName = "Linéaire"
cardFadeOutFrames = 30
cardFadeOutTransitionStyleName = "Linéaire"

[[contentStyle]]
name = "Colonnes"
blockOrientation = "HORIZONTAL"
spineAttachment = "HEAD_GAP_CENTER"
vMarginTopPx = 0.0
vMarginBottomPx = 0.0
bodyLetterStyleName = "Nom"
bodyLayout = "GRID"
sort = "OFF"
gridCols = 1
gridStructure = "FREE"
gridHarmonizeColWidths = "ACROSS_BLOCKS"
gridHarmonizeRowHeight = "OFF"
gridCellHJustifyPerCol = ["LEFT", ]
gridRowGapPx = 0.0
hasHead = true
headLetterStyleName = "Petit"
headHarmonizeWidth = "ACROSS_BLOCKS"
headHJustify = "RIGHT"
headVShelve = "FIRST"
headVJustify = "MIDDLE"
headGapPx = 32.0
headLeader = ""
hasTail = false

[[contentStyle]]
name = "Écran"
blockOrientation = "VERTICAL"
spineAttachment = "BODY_CENTER"
vMarginTopPx = 0.0
vMarginBottomPx = 0.0
bodyLetterStyleName = "Nom de l’écran"
bodyLayout = "GRID"
sort = "OFF"
gridCols = 1
gridStructure = "FREE"
gridHarmonizeColWidths = "OFF"
gridHarmonizeRowHeight = "OFF"
gridCellHJustifyPerCol = ["CENTER", ]
gridRowGapPx = 0.0
hasHead = true
headLetterStyleName = "Petit écran"
headHJustify = "CENTER"
headGapPx = 32.0
hasTail = true
tailLetterStyleName = "Petit écran"
tailHJustify = "CENTER"
tailGapPx = 32.0

[[contentStyle]]
name = "Logos"
spineAttachment = "BODY_CENTER"
vMarginTopPx = 0.0
vMarginBottomPx = 0.0
bodyLetterStyleName = "Normal"
bodyLayout = "FLOW"
sort = "OFF"
flowDirection = "L2R"
flowLineHJustify = "CENTER"
flowSquareCells = false
flowHarmonizeCellWidth = "OFF"
flowHarmonizeCellHeight = "OFF"
flowCellVJustify = "MIDDLE"
flowLineWidthPx = 1200.0
flowLineGapPx = 64.0
flowHGapPx = 96.0
flowSeparator = ""
hasHead = false
hasTail = false

[[contentStyle]]
name = "Musique"
blockOrientation = "VERTICAL"
spineAttachment = "BODY_CENTER"
vMarginTopPx = 0.0
vMarginBottomPx = 0.0
bodyLetterStyleName = "Petit"
bodyLayout = "GRID"
sort = "OFF"
gridCols = 1
gridStructure = "FREE"
gridHarmonizeColWidths = "OFF"
gridHarmonizeRowHeight = "OFF"
gridCellHJustifyPerCol = ["CENTER", ]
gridRowGapPx = 0.0
hasHead = true
headLetterStyleName = "Titre de chanson"
headHJustify = "CENTER"
headGapPx = 16.0
hasTail = false

[[contentStyle]]
name = "Points"
blockOrientation = "VERTICAL"
spineAttachment = "BODY_CENTER"
vMarginTopPx = 0.0
vMarginBottomPx = 0.0
bodyLetterStyleName = "Nom"
bodyLayout = "FLOW"
sort = "OFF"
flowDirection = "L2R"
flowLineHJustify = "CENTER"
flowSquareCells = false
flowHarmonizeCellWidth = "OFF"
flowHarmonizeCellHeight = "OFF"
flowCellVJustify = "MIDDLE"
flowLineWidthPx = 800.0
flowLineGapPx = 0.0
flowHGapPx = 32.0
flowSeparator = "•"
flowSeparatorVJustify = "MIDDLE"
hasHead = true
headLetterStyleName = "Petit"
headHJustify = "CENTER"
headGapPx = 12.0
hasTail = false

[[contentStyle]]
name = "Résumé"
spineAttachment = "BODY_CENTER"
vMarginTopPx = 0.0
vMarginBottomPx = 0.0
bodyLetterStyleName = "Normal"
bodyLayout = "PARAGRAPHS"
paragraphsLineHJustify = "CENTER"
paragraphsLineWidthPx = 500.0
paragraphsParaGapPx = 8.0
paragraphsLineGapPx = 0.0
hasHead = false
hasTail = false

[[contentStyle]]
name = "Sous-titre"
spineAttachment = "BODY_CENTER"
vMarginTopPx = 0.0
vMarginBottomPx = 0.0
bodyLetterStyleName = "Petit"
bodyLayout = "GRID"
sort = "OFF"
gridCols = 1
gridStructure = "FREE"
gridHarmonizeColWidths = "OFF"
gridHarmonizeRowHeight = "OFF"
gridCellHJustifyPerCol = ["CENTER", ]
gridRowGapPx = 0.0
hasHead = false
hasTail = false

[[contentStyle]]
name = "Tabulation"
spineAttachment = "BODY_CENTER"
vMarginTopPx = 0.0
vMarginBottomPx = 0.0
bodyLetterStyleName = "Nom"
bodyLayout = "GRID"
sort = "OFF"
gridCols = 3
gridFillingOrder = "L2R_T2B"
gridFillingBalanced = true
gridStructure = "EQUAL_WIDTH_COLS"
gridHarmonizeColWidths = "OFF"
gridHarmonizeRowHeight = "OFF"
gridCellHJustifyPerCol = ["LEFT", "CENTER", "RIGHT", ]
gridCellVJustify = "MIDDLE"
gridRowGapPx = 0.0
gridColGapPx = 32.0
hasHead = false
hasTail = false

[[contentStyle]]
name = "Titre"
spineAttachment = "BODY_CENTER"
vMarginTopPx = 0.0
vMarginBottomPx = 0.0
bodyLetterStyleName = "Titre"
bodyLayout = "GRID"
sort = "OFF"
gridCols = 1
gridStructure = "FREE"
gridHarmonizeColWidths = "OFF"
gridHarmonizeRowHeight = "OFF"
gridCellHJustifyPerCol = ["CENTER", ]
gridRowGapPx = 0.0
hasHead = false
hasTail = false

[[letterStyle]]
name = "Nom"
font = "Archivo Narrow Bold"
heightPx = 42.0
leadingTopRh = 0.0
leadingBottomRh = 0.0
trackingEm = 0.0
kerning = true
ligatures = true
uppercase = false
smallCaps = "OFF"
superscript = "OFF"
hScaling = 1.0

	[[letterStyle.layers]]
	name = "Texte"
	coloring = "PLAIN"
	color1 = [0.98, 0.941, 0.902, 1.0, ]
	shape = "TEXT"
	dilationRfh = 0.0
	contour = false
	offsetCoordinateSystem = "CARTESIAN"
	hOffsetRfh = 0.0
	vOffsetRfh = 0.0
	hScaling = 1.0
	vScaling = 1.0
	hShearing = 0.0
	vShearing = 0.0
	blurRadiusRfh = 0.0

[[letterStyle]]
name = "Nom de l’écran"
font = "Archivo Narrow Bold"
heightPx = 120.0
leadingTopRh = 0.0
leadingBottomRh = 0.0
trackingEm = 0.02
kerning = true
ligatures = true
uppercase = false
smallCaps = "OFF"
superscript = "OFF"
hScaling = 1.0

	[[letterStyle.layers]]
	name = "Texte"
	coloring = "PLAIN"
	color1 = [0.98, 0.941, 0.902, 1.0, ]
	shape = "TEXT"
	dilationRfh = 0.0
	contour = false
	offsetCoordinateSystem = "CARTESIAN"
	hOffsetRfh = 0.0
	vOffsetRfh = 0.0
	hScaling = 1.0
	vScaling = 1.0
	hShearing = 0.0
	vShearing = 0.0
	blurRadiusRfh = 0.0

[[letterStyle]]
name = "Normal"
font = "Archivo Narrow Regular"
heightPx = 40.0
leadingTopRh = 0.0
leadingBottomRh = 0.0
trackingEm = 0.0
kerning = true
ligatures = true
uppercase = false
smallCaps = "OFF"
superscript = "OFF"
hScaling = 1.0

	[[letterStyle.layers]]
	name = "Texte"
	coloring = "PLAIN"
	color1 = [0.98, 0.941, 0.902, 1.0, ]
	shape = "TEXT"
	dilationRfh = 0.0
	contour = false
	offsetCoordinateSystem = "CARTESIAN"
	hOffsetRfh = 0.0
	vOffsetRfh = 0.0
	hScaling = 1.0
	vScaling = 1.0
	hShearing = 0.0
	vShearing = 0.0
	blurRadiusRfh = 0.0

[[letterStyle]]
name = "Petit"
font = "Archivo Narrow Regular"
heightPx = 36.0
leadingTopRh = 0.0
leadingBottomRh = 0.0
trackingEm = 0.0
kerning = true
ligatures = true
uppercase = false
smallCaps = "OFF"
superscript = "OFF"
hScaling = 1.0

	[[letterStyle.layers]]
	name = "Texte"
	coloring = "PLAIN"
	color1 = [0.851, 0.831, 0.8, 1.0, ]
	shape = "TEXT"
	dilationRfh = 0.0
	contour = false
	offsetCoordinateSystem = "CARTESIAN"
	hOffsetRfh = 0.0
	vOffsetRfh = 0.0
	hScaling = 1.0
	vScaling = 1.0
	hShearing = 0.0
	vShearing = 0.0
	blurRadiusRfh = 0.0

[[letterStyle]]
name = "Petit écran"
font = "Archivo Narrow Regular"
heightPx = 65.0
leadingTopRh = 0.0
leadingBottomRh = 0.0
trackingEm = 0.0
kerning = true
ligatures = true
uppercase = false
smallCaps = "OFF"
superscript = "OFF"
hScaling = 1.0

	[[letterStyle.layers]]
	name = "Texte"
	coloring = "PLAIN"
	color1 = [0.851, 0.831, 0.8, 1.0, ]
	shape = "TEXT"
	dilationRfh = 0.0
	contour = false
	offsetCoordinateSystem = "CARTESIAN"
	hOffsetRfh = 0.0
	vOffsetRfh = 0.0
	hScaling = 1.0
	vScaling = 1.0
	hShearing = 0.0
	vShearing = 0.0
	blurRadiusRfh = 0.0

[[letterStyle]]
name = "Titre"
font = "Archivo Narrow Regular"
heightPx = 68.0
leadingTopRh = 0.0
leadingBottomRh = 0.0
trackingEm = 0.08
kerning = true
ligatures = true
uppercase = false
smallCaps = "OFF"
superscript = "OFF"
hScaling = 1.0

	[[letterStyle.layers]]
	name = "Texte"
	coloring = "PLAIN"
	color1 = [1.0, 0.98, 0.804, 1.0, ]
	shape = "TEXT"
	dilationRfh = 0.0
	contour = false
	offsetCoordinateSystem = "CARTESIAN"
	hOffsetRfh = 0.0
	vOffsetRfh = 0.0
	hScaling = 1.0
	vScaling = 1.0
	hShearing = 0.0
	vShearing = 0.0
	blurRadiusRfh = 0.0

[[letterStyle]]
name = "Titre de chanson"
font = "Archivo Narrow Bold"
heightPx = 42.0
leadingTopRh = 0.0
leadingBottomRh = 0.0
trackingEm = 0.04
kerning = true
ligatures = true
uppercase = false
smallCaps = "SMALL_CAPS"
superscript = "OFF"
hScaling = 1.0

	[[letterStyle.layers]]
	name = "Texte"
	coloring = "PLAIN"
	color1 = [1.0, 0.98, 0.804, 1.0, ]
	shape = "TEXT"
	dilationRfh = 0.0
	contour = false
	offsetCoordinateSystem = "CARTESIAN"
	hOffsetRfh = 0.0
	vOffsetRfh = 0.0
	hScaling = 1.0
	vScaling = 1.0
	hShearing = 0.0
	vShearing = 0.0
	blurRadiusRfh = 0.0

[[transitionStyle]]
name = "Linéaire"
graph = [0.0, 0.0, 1.0, 1.0, ]

[[pictureStyle]]
name = "Cinecred H"
picture = "Cinecred H.svg"
heightPx = 90.0
cropBlankSpace = true

[[pictureStyle]]
name = "Cinecred V"
picture = "Cinecred V.svg"
heightPx = 150.0
cropBlankSpace = true

[[pictureStyle]]
name = "Nouvelle image"
picture = "frame.jpg"

[[tapeStyle]]
name = "Nouvelle vidéo"
tape = "0125-0200.mkv"
widthPx = 1920
heightPx = 1080
slice = "00:00:00+00-00:00:00+00"
temporallyJustify = "LEFT"
leftTemporalMarginFrames = 0
rightTemporalMarginFrames = 0
fadeInFrames = 0
fadeOutFrames = 0

